### ISSUE TITLE
Cloud foundry auth failed

### ISSUE THREAD

**Issue by zhoutiekui** [cloudfoundry/uaa-release#54]
UAA version:  24.5
When I login to cf ,encounter an error as below。 anybody who knows the reason? is there an workaround ,thanks.

[2017-03-10 09:32:18.338] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] ....  INFO --- Version: HV000001: Hibernate Validator 4.3.1.Final
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator: Can't construct a java object for tag:yaml.org,2002:org.cloudfoundry.identity.uaa.impl.config.UaaConfiguration; exception=Cannot create property=oauth for JavaBean=org.cloudfoundry.identity.uaa.impl.config.UaaConfiguration@474ebb7e; Cannot create property=clients for JavaBean=org.cloudfoundry.identity.uaa.impl.config.UaaConfiguration$OAuth@75ec3deb; Cannot create property=name for JavaBean=org.cloudfoundry.identity.uaa.impl.config.UaaConfiguration$OAuthClient@2e3f26e9; Unable to find property 'name' on class: org.cloudfoundry.identity.uaa.impl.config.UaaConfiguration$OAuthClient
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:  in 'string', line 1, column 1:
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:     scim:
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:     ^
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:333)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.yaml.snakeyaml.Yaml.load(Yaml.java:400)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.cloudfoundry.identity.uaa.impl.config.YamlConfigurationValidator.afterPropertiesSet(YamlConfigurationValidator.java:86)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:756)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:668)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:634)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:682)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:553)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:494)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at javax.servlet.GenericServlet.init(GenericServlet.java:158)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.cloudfoundry.identity.uaa.web.RecognizeFailureDispatcherServlet.init(RecognizeFailureDispatcherServlet.java:56)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1238)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1151)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1038)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4997)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5289)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:939)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1812)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at java.lang.Thread.run(Thread.java:745)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator: Caused by: org.yaml.snakeyaml.error.YAMLException: Cannot create property=oauth for JavaBean=org.cloudfoundry.identity.uaa.impl.config.UaaConfiguration@474ebb7e; Cannot create property=clients for JavaBean=org.cloudfoundry.identity.uaa.impl.config.UaaConfiguration$OAuth@75ec3deb; Cannot create property=name for JavaBean=org.cloudfoundry.identity.uaa.impl.config.UaaConfiguration$OAuthClient@2e3f26e9; Unable to find property 'name' on class: org.cloudfoundry.identity.uaa.impl.config.UaaConfiguration$OAuthClient
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:299)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:189)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:331)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    ... 41 more
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator: Caused by: org.yaml.snakeyaml.error.YAMLException: Cannot create property=clients for JavaBean=org.cloudfoundry.identity.uaa.impl.config.UaaConfiguration$OAuth@75ec3deb; Cannot create property=name for JavaBean=org.cloudfoundry.identity.uaa.impl.config.UaaConfiguration$OAuthClient@2e3f26e9; Unable to find property 'name' on class: org.cloudfoundry.identity.uaa.impl.config.UaaConfiguration$OAuthClient
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:299)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:189)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:296)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    ... 43 more
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator: Caused by: org.yaml.snakeyaml.error.YAMLException: Cannot create property=name for JavaBean=org.cloudfoundry.identity.uaa.impl.config.UaaConfiguration$OAuthClient@2e3f26e9; Unable to find property 'name' on class: org.cloudfoundry.identity.uaa.impl.config.UaaConfiguration$OAuthClient
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:299)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:189)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:325)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:145)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:306)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:170)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:296)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    ... 46 more
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator: Caused by: org.yaml.snakeyaml.error.YAMLException: Unable to find property 'name' on class: org.cloudfoundry.identity.uaa.impl.config.UaaConfiguration$OAuthClient
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:132)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:121)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.getProperty(Constructor.java:308)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.cloudfoundry.identity.uaa.impl.config.CustomPropertyConstructor$CustomPropertyConstructMapping.getProperty(CustomPropertyConstructor.java:71)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:240)
[2017-03-10 09:32:18.391] cloudfoundry-identity-server/uaa - ???? [127.0.0.1-startStop-1] .... ERROR --- YamlConfigurationValidator:    ... 54 more

**Comment by tnwang** [comment]
This error is usually related to incorrectly set value in the YAML config.

The likely culprit timeline wise is https://github.com/cloudfoundry/uaa-release/releases/tag/v23 which requires explicitly defined SAML Provider keys.
