### ISSUE TITLE
v53: java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by jochenehret** [cloudfoundry/uaa-release#80]
Hi,

we are using UAA release v53 with the default memory settings: `export CATALINA_OPTS="-Xmx768m -XX:MaxMetaspaceSize=256m"`
Now we got an OutOfMemoryError:
```
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.Arrays.copyOf(Arrays.java:3332)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
        at java.lang.StringBuilder.append(StringBuilder.java:136)
        at java.lang.StackTraceElement.toString(StackTraceElement.java:172)
        at java.lang.String.valueOf(String.java:2994)
        at java.lang.StringBuilder.append(StringBuilder.java:131)
        at java.lang.Throwable.printStackTrace(Throwable.java:658)
        at java.lang.Throwable.printStackTrace(Throwable.java:643)
        at org.apache.tomcat.jdbc.pool.ConnectionPool.getStackTrace(ConnectionPool.java:1117)
        at org.apache.tomcat.jdbc.pool.ConnectionPool.getThreadDump(ConnectionPool.java:1103)
        at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:807)
        at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:651)
        at org.apache.tomcat.jdbc.pool.ConnectionPool.getConnection(ConnectionPool.java:198)
        at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:132)
        at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111)
        at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:77)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:619)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:684)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:716)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:766)
        at org.cloudfoundry.identity.uaa.scim.jdbc.JdbcScimGroupMembershipManager.getGroupsWithMember(JdbcScimGroupMembershipManager.java:239)
        at org.cloudfoundry.identity.uaa.scim.jdbc.JdbcScimGroupMembershipManager.getGroupsWithMember(JdbcScimGroupMembershipManager.java:262)
        at org.cloudfoundry.identity.uaa.scim.jdbc.JdbcScimGroupMembershipManager.getGroupsWithMember(JdbcScimGroupMembershipManager.java:262)
        at org.cloudfoundry.identity.uaa.scim.jdbc.JdbcScimGroupMembershipManager.getGroupsWithMember(JdbcScimGroupMembershipManager.java:226)
        at org.cloudfoundry.identity.uaa.scim.endpoints.ScimUserEndpoints.syncGroups(ScimUserEndpoints.java:476)
        at org.cloudfoundry.identity.uaa.scim.endpoints.ScimUserEndpoints.findUsers(ScimUserEndpoints.java:410)
        at org.cloudfoundry.identity.uaa.scim.endpoints.ScimUserEndpoints$$FastClassBySpringCGLIB$$d564cbce.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
```
After restarting, the UAA server worked again. Is it possible to find the root cause for this issue? Is it related to the "performance issue" mentioned in the v53 release notes?

Thanks for your support and best Regards,

  Jochen.

**Comment by fhanik** [comment]
@jochenehret Thank you for the report. It does not appear to be related to the issue in v53.

`GC overhead limit exceeded` indicates an exceptionally large number of objects being created and then collected by the garbage collector in a short amount of time. 

Questions
- What operation are you running? 
- This trace seems to indicate that it is `GET /Users`, is that correct?
- Is that operation expected to return a large number of users?

If you've answered yes to the questions above, that operation can be greatly optimized by not requesting user groups to be returned with each user. Perform a request with a list of attributes and do _not_ include _groups_ or _approvals_ as part of your `GET /Users?attributes=id,username`. This will reduce the number of queries your request does from N (number of users returned) to 1.

https://docs.cloudfoundry.org/api/uaa/version/4.8.0/index.html#list-with-attribute-filtering

additionally, the stack trace seems to indicate that the JVM complains when the connection pool is recording the trace of the request. 

You can disable this recording by setting `uaa.database.log_abandoned: false`

https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/spec#L696-L698

I'd encourage you to implement both of these optimization. If the error still happens I will ask for your cooperation to help diagnose the root cause.

**Comment by fhanik** [comment]
@jochenehret Can I also ask you to add the 
```
-XX:HeapDumpOnOutOfMemoryError
```
options to your JVM parameters
https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/spec#L108-L110

This may or may not give us the root cause for the error depending on what the JVM does before the dump occurs. But it's worth having there.

**Comment by jochenehret** [comment]
@fhanik Thanks for your quick reply, I'll check what queries we run and we'll apply the suggested optimizations.

Best Regards,

 Jochen.

**Comment by sreetummidi** [comment]
Please re-open if you are still seeing errors
